spring:
  application:
    name: spring-mcp-client
  main:
    web-application-type: none
  ai:
    openai:
      api-key: xxxx
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-turbo

    mcp:
      client:
        toolcallback:
          enabled : true
        sse:
          connections:
            server1:
              url: http://127.0.0.1:8080
        version: 1.0.0
